sigma: 3.65
eps: 0.014
n_cells: 4
rho_star: 2.0
cell_param_a: null
dt: 0.005
r_cutoff: 2.5
r_skin: 3.0
equil_steps: 2000
prod_steps: 6000
rescale_interval: 10
rdf_interval: 10
rdf_bins: 200
t_star_values:
- 2.0
n_workers: 1
trajectory_interval: 2
render_interval: 2
frames_per_T_star: 200
save_positions: false
save_velocities: false
